// Radix UI Components Generated by AstroBits Core MCP System
// These are the primitive components that Shadcn/UI is built upon

export { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from './accordion';
export { 
  Dialog, 
  DialogPortal, 
  DialogOverlay, 
  DialogClose, 
  DialogTrigger, 
  DialogContent, 
  DialogHeader, 
  DialogFooter, 
  DialogTitle, 
  DialogDescription 
} from './dialog';
export { Tabs, TabsList, TabsTrigger, TabsContent } from './tabs';

// Usage:
// import { Accordion, Dialog, Tabs } from '@/components/radix';
