// Test Components Generated by AstroBits Core MCP System
// These components demonstrate the capabilities of different MCP servers

export { default as TestButton } from './shadcn-ui-button';
export { default as TestCard } from './aceternity-ui-card';
export { default as TestHero } from './magic-ui-hero';

// Usage:
// import { TestButton, TestCard, TestHero } from './test-components';
