export default function TestHero() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-900 via-purple-900 to-indigo-900 flex items-center justify-center">
      <div className="text-center text-white p-8">
        <h1 className="text-6xl font-bold mb-6 bg-gradient-to-r from-blue-400 to-purple-400 bg-clip-text text-transparent">
          Magic UI Hero
        </h1>
        <p className="text-xl mb-8 text-gray-300 max-w-2xl mx-auto">
          This is a test hero section that would typically be generated by Magic UI.
          It showcases the kind of complex layouts and designs that Magic UI can create.
        </p>
        <div className="space-x-4">
          <button className="bg-blue-600 hover:bg-blue-700 text-white font-bold py-3 px-6 rounded-lg transition-colors">
            Get Started
          </button>
          <button className="border border-white text-white hover:bg-white hover:text-black font-bold py-3 px-6 rounded-lg transition-colors">
            Learn More
          </button>
        </div>
      </div>
    </div>
  );
}