// Aceternity UI Components Generated by AstroBits Core MCP System
// These are animated and interactive components

export { HoverEffect, Card, CardTitle, CardDescription } from './card-spotlight';
export { Hate } from './hate';
export { MacbookScroll } from './macbook-scroll';

// Usage:
// import { HoverEffect, Hate, MacbookScroll } from '@/components/aceternity';
