// Aceternity UI Components Generated by AstroBits Core MCP System
// These are animated and interactive components

export { HoverEffect, Card, CardTitle, CardDescription } from './card-spotlight';
export { Hate } from './hate';
export { MacbookScroll } from './macbook-scroll';
export { ThreeDCardDemo } from './3d-card-demo';

// Usage:
// import { HoverEffect, Hate, MacbookScroll, ThreeDCardDemo } from '@/components/aceternity';
